"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SEARCH_CONVERSATIONS = exports.SET_NEW_MESSAGE = exports.SET_MESSAGES = exports.SET_CONVERSATIONS = exports.SET_SELECTED_CONVERSATION = exports.SET_SEARCHED_USERS = exports.SET_CHAT_OPEN = exports.SET_COLOR = exports.SET_THEME = exports.SET_PENDING = exports.SET_SUCCESS = exports.SET_ERROR = exports.SET_ACCESS_TOKEN = exports.SET_AUTHENTICATED_USER = exports.SET_AUTHENTICATED = void 0;
// user reducer types
exports.SET_AUTHENTICATED = "SET_AUTHENTICATED";
exports.SET_AUTHENTICATED_USER = "SET_AUTHENTICATED_USER";
exports.SET_ACCESS_TOKEN = "SET_ACCESS_TOKEN";
// UI reducer types
exports.SET_ERROR = "SET_ERROR";
exports.SET_SUCCESS = "SET_SUCCESS";
exports.SET_PENDING = "SET_PENDING";
exports.SET_THEME = "SET_THEME";
exports.SET_COLOR = "SET_COLOR";
exports.SET_CHAT_OPEN = "SET_IS_CHAT_OPEN";
// data reducer types
exports.SET_SEARCHED_USERS = "SET_SEARCHED_USERS";
exports.SET_SELECTED_CONVERSATION = "SET_SELECTED_CONVERSATION";
exports.SET_CONVERSATIONS = "SET_CONVERSATIONS";
exports.SET_MESSAGES = "SET_MESSAGES";
exports.SET_NEW_MESSAGE = "SET_NEW_MESSAGE";
exports.SEARCH_CONVERSATIONS = "SEARCH_CONVERSATIONS";
